name: roundup_app
description: UPI Roundup Investing App (Flutter)
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  fl_chart: ^0.68.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10
  lottie: ^3.1.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
