apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcon-frontend
  labels:
    app: arcon-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arcon-frontend
  template:
    metadata:
      labels:
        app: arcon-frontend
    spec:
      containers:
      - name: frontend
        image: bansalsahab/arcon-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: arcon-frontend
spec:
  selector:
    app: arcon-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
